from django.urls import path

from . import views

urlpatterns = [
    path('signin/', views.signin),
    path('signup/', views.signup),
    path('indexadmin/', views.indexadmin),
    path('header1/', views.header1),
    path('logoutadmin/', views.logoutadmin),
    path('resetad/', views.resetad),
    path('forgotad/', views.forgotad),
    path('addcity/', views.addcity),
    path('showcity/', views.showcity),
    path('editcity/<int:id>/', views.editcity),
    path('updatecity/<int:id>/', views.updatecity),
    path('deletecity/<int:id>/', views.deletecity),
    path('category/', views.category),
    path('showcat/', views.showcat),
    path('editcat/<int:id>/', views.editcat),
    path('updatecat/<int:id>/', views.updatecat),
    path('deletecat/<int:id>/', views.deletecat),
    path('subcat/', views.subcat),
    path('showsubcat/', views.showsubcat),
    path('editsubcat/<int:id>/', views.editsubcat),
    path('updatesubcat/<int:id>/', views.updatesubcat),
    path('changepw/', views.changepw),
    path('changepw1/', views.changepw1),
    path('reservation/', views.reservation),
    path('addpro/', views.addpro),
    path('prolist/', views.prolist),
    path('editpro/<int:id>/', views.editpro),
    path('updatepro/<int:id>/', views.updatepro),
    path('deletepro/<int:id>/', views.deletepro),
    path('vprofile/', views.vprofile),
    path('profile/', views.profile),
    path('ajax/load-sub/', views.load_sub, name='ajax_load_cities'),
    path('deletereserve/<int:id>/', views.deletereserve),
    path('order1/', views.order1),
    path('orderdetail1/<int:id>/', views.orderdetail1),
]