# Generated by Django 4.1.6 on 2023-03-25 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_details',
            old_name='customer',
            new_name='custom',
        ),
    ]
