# Generated by Django 4.1.6 on 2023-03-25 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0002_rename_customer_order_details_custom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_details',
            old_name='custom',
            new_name='customer',
        ),
    ]
