# Generated by Django 4.1.6 on 2023-03-24 13:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proname', models.CharField(max_length=100)),
                ('prod', models.CharField(max_length=800)),
                ('pimg', models.FileField(upload_to='')),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Invalid Email')])),
                ('contact', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=800)),
                ('password', models.CharField(max_length=8)),
                ('c_password', models.CharField(max_length=10)),
                ('otp', models.CharField(max_length=10, null=True)),
                ('otp_used', models.IntegerField(null=True)),
                ('img', models.FileField(default='userd.png', upload_to='assets/images/products/')),
            ],
            options={
                'db_table': 'Adminsignup',
            },
        ),
        migrations.CreateModel(
            name='sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.cat')),
            ],
        ),
    ]
