# Generated by Django 4.1.6 on 2023-03-24 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
        ('clientapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='city_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientapp.city'),
        ),
        migrations.AddField(
            model_name='product',
            name='Category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.cat'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.sub'),
        ),
    ]
